### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by JoelitonMods** [0NullBit0/NullTrace-Android-Inject#1]
There was an error here, could you tell me why?

![image](https://github.com/0NullBit0/NullTrace-Android-Inject/assets/90171592/be4a2766-f9fa-4cae-bc08-ceab941fd94c)

**Comment by JoelitonMods** [comment]
> O erro parece estar ao obter e definir regs.
> 
> Isso pode ser devido a vários motivos pelos quais você está usando a instância Nougat32, se eu a ver corretamente? Se sim, você também precisa executar o binário x86 e não o binário x86_64, pois isso fará uma chamada na qual os sistemas de 32 bits falharão.
> 
> Se isso não funcionou, você pode me dizer a versão específica do bluestacks do método root e o jogo/lib para eu reproduzir? Verifique também se o seu nullinjector é o mais novo, eu o atualizei recentemente

I used binary x86 correctly the game I'm trying is Garena Free Fire Updated version 32 bytes bluestacks version is the most updated Nougat32 instance

**Comment by 0NullBit0** [comment]
ok i tried doing the same and run into some other issues i were able to fix and update. For me i successfully injected into freefire in n32 instance
![Screenshot 2024-02-06 120322](https://github.com/0NullBit0/NullTrace-Android-Inject/assets/131892100/1b185c87-b08d-4157-aea7-986903a3128f)
![Screenshot 2024-02-06 120348](https://github.com/0NullBit0/NullTrace-Android-Inject/assets/131892100/351bd816-36b0-471e-a650-2933831c6a26)
You can try again now with the new one but for you it fails to get regs. Is there any way for you to use pie64 or nougat64 instance?

**Comment by JoelitonMods** [comment]
> Proprietário

it worked thank you very much
