### ISSUE TITLE
DlError message: dlopen failed: library

### ISSUE THREAD

**Issue by 350030173** [0NullBit0/NullTrace-Android-Inject#2]
DlError message: dlopen failed: library "./libfrida-gadget.so" not found
libfrida-gadget.so is frida-gadget
![1111](https://github.com/0NullBit0/NullTrace-Android-Inject/assets/20263746/b1d89a68-e65b-430f-b6bb-79e1b2378db1)

**Comment by 0NullBit0** [comment]
Use a full path like /data/local/tmp/libfrida-gadget.so

**Comment by 0NullBit0** [comment]
if theres nothing more from you i'll close this since a valid path would fix this issue...

**Comment by MikaCybertron** [comment]
does this work for any device than emulator?

**Comment by 0NullBit0** [comment]
yes not tested yet but in theory it should work for real devices too

> does this work for any device for real phone than emulator?
